### ISSUE TITLE
docker-compose安装rabbitmq

### ISSUE THREAD

**Issue by huangxiaobo** [huangxiaobo/huangxiaobo.github.io#7]
```
    rabbitmq:
        # image: "rabbitmq"
        image: "rabbitmq:management"
        # hostname: "rabbit1"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
            RABBITMQ_LOG_BASE: "/var/log/rabbitmq"
        ports:
            - "15672:15672"
            - "5672:5672"
        labels:
            NAME: "rabbitmq"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
```

注意：
1.如果image是"rabbitmq" 那么是不带管理也没的， “rabbitmq:manangement” 带管理页面， 可以登录web查看
2. 查看管理页面方法： http://container-ip:15672
3. 此镜像默认用户rabbitmq:rabbitmq

**Comment by huangxiaobo** [comment]
```
    rabbitmq:
        # image: "rabbitmq"
        image: "rabbitmq:management"
        # hostname: "rabbit1"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
            RABBITMQ_LOG_BASE: "/var/log/rabbitmq"
        ports:
            - "15672:15672"
            - "5672:5672"
        labels:
            NAME: "rabbitmq"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
```

注意：
1.如果image是"rabbitmq" 那么是不带管理页面的， “rabbitmq:manangement” 带管理页面， 可以登录web查看
2. 查看管理页面方法： http://container-ip:15672
3. 此镜像默认用户rabbitmq:rabbitmq
